# Generated by Django 3.1.5 on 2021-01-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SalonAutomobila', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobil',
            name='naziv',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
